spring:
  datasource:
    url: jdbc:mariadb://i10a206.p.ssafy.io:3306/mogul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    mongodb:
      uri: mongodb://root:1234@i10a206.p.ssafy.io:27017/
      database: mogul
app:
  front:
    server: http://i10a206.p.ssafy.io:3000