spring:
  datasource:
    url: jdbc:mariadb://[host]:[port]/mogul
    driver-class-name: org.mariadb.jdbc.Driver
    username: username
    password: password
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    mongodb:
      uri: mongodb://[username]:[password]@[host]:[port]/
      database: mogul
    redis:
      host: host
      port: 6379

elastic:
  host: host
  username: username
  password: password

logging:
  level:
    org:
      springframework:
        security:
          DEBUG
jwt:
  secret: secret-key